#!/usr/bin/env bash
# Runs an endless loop printing "To infinity and beyond" and prints a message on SIGTERM

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
